### ISSUE TITLE
 Tela caixa de entrada/emails Nº20

### ISSUE THREAD

**Issue by TSjadness** [Itatech-Jr/Modern-School-UI#17]
Criada a tela do administrador no figma na versao mobile.

**Comment by Ericles-Porty** [comment]
O nome da issue e do PR não condiz com o que foi feito, é uma caixa de email e não uma tela de administrador, a versão mobile só tera professor e aluno como usuário. Mas isso não chega a ser impeditivo, porém presta atenção na próxima. @joannestephany não percebeu isso?
