### ISSUE TITLE
Desenvolver versão mobile da tela Web\ Web\TelaManterAlunoEManterTurma\ManterTurma\Tela_029

### ISSUE THREAD

**Issue by Gabrielx47** [Itatech-Jr/Modern-School-UI#38]

**Comment by Ericles-Porty** [comment]
Se atentar que é para desenvolver apenas o pop-up de exclusão 
![image](https://user-images.githubusercontent.com/67772327/210458075-0de35965-1329-487b-840e-ecb92aaba1d8.png)
![image](https://user-images.githubusercontent.com/67772327/210458079-ff06f71b-7bcf-446b-83fd-fa5e936a3318.png)
