### ISSUE TITLE
Desenvolver versão mobile da tela Web\ Web\TelaManterAlunoEManterTurma\ManterTurma\Tela_028

### ISSUE THREAD

**Issue by Gabrielx47** [Itatech-Jr/Modern-School-UI#40]

**Comment by Ericles-Porty** [comment]
![image](https://user-images.githubusercontent.com/67772327/210458758-c04fdd16-011d-4ace-ac11-90628c8a218b.png)
Se atentar que é apenas o pop-up de excluir e o pop-up de confirmação de exclusão.
